# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/database/schema.rs"
custom_type_derives = ["Clone", "diesel::query_builder::QueryId"]

[migrations_directory]
dir = "/home/jpc/Informatique/Projets/Utilitaires/gnucash-toolbox/migrations"
