# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "gnc-db-schema/src/lib.rs"
custom_type_derives = ["Clone", "diesel::query_builder::QueryId"]

[migrations_directory]
dir = "gnc-db-schema/migrations"
